cart/urls.py
from django.urls import path
from . import views
from .views import update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:package_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('view/', views.view_cart, name='cart_view'),
    path('update/<int:item_id>/', update_cart, name='update_cart'),

]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('checkout/', views.process_checkout, name='checkout'),
    path('checkout/success/<int:order_id>/', views.checkout_success, name='checkout_success'),
    path('validate_discount/<str:discount_code>/', views.validate_discount, name='validate_discount'),
]

highlands/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('packages/', include('packages.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
     path('checkout/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from packages.models import Package
from user.models import CustomUser


class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.package.title} in {self.user}'s cart"

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart
from packages.models import Package


def add_to_cart(request, package_id):
    package = Package.objects.get(pk=package_id)
    user = request.user

    existing_cart_item, created = Cart.objects.get_or_create(
        user=user, package=package)

    if not created:
        existing_cart_item.quantity += 1
        existing_cart_item.save()

    return redirect('cart:cart_view')


def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(Cart, id=item_id)
    cart_item.delete()

    return redirect('cart:cart_view')


def view_cart(request):
    user = request.user
    cart_items = Cart.objects.filter(user=user)
    total_price = sum(item.package.price *
                      item.quantity for item in cart_items)

    return render(request, 'cart/cart.html', {'cart_items': cart_items, 'total_price': total_price})


def update_cart(request, item_id):
    cart_item = get_object_or_404(Cart, id=item_id)

    if request.method == 'POST':
        new_quantity = int(request.POST.get('quantity'))
        if new_quantity > 0:
            cart_item.quantity = new_quantity
            cart_item.save()

    return redirect('cart:cart_view')

cart/templates/cart/cart.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Your Cart</h1>

    {% if cart_items %}
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% for item in cart_items %}
                <li class="list-group-item">
                    <div class="d-flex flex-column">
                        <div class="mb-2">
                            <h5>{{ item.package.title }}</h5>
                        </div>
                        <div class="mb-2">
                            <p class="mb-0">Quantity</p>
                        </div>
                        <div class="mb-2">
                            <form method="post" action="{% url 'cart:update_cart' item.id %}" class="update-form">
                                {% csrf_token %}
                                <div class="input-group">
                                    <input type="number" name="quantity" value="{{ item.quantity }}" min="1" class="form-control quantity-input-small mx-auto">
                                </div>
                                <div class="mt-2">
                                    <button type="submit" class="btn btn-outline-secondary">Update Quantity</button>
                                </div>
                            </form>
                        </div>
                        <div>
                            <form method="post" action="{% url 'cart:remove_from_cart' item.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">Remove</button>
                            </form>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Total Price</h5>
                    <p class="card-text">£ {{ total_price }}</p>
                    <ul class="shopping-list">
                        {% for item in cart_items %}
                            <li>{{ item.package.title }} - Quantity: {{ item.quantity }}</li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'checkout:checkout' %}" class="btn btn-success btn-block">Proceed to Checkout</a>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="alert alert-info" role="alert">
        Your cart is empty.
    </div>
    {% endif %}
</div>
{% endblock %}