cart/urls.py
from django.urls import path
from . import views
from .views import update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:package_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('view/', views.view_cart, name='cart_view'),
    path('update/<int:item_id>/', update_cart, name='update_cart'),

]

checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('checkout/', views.process_checkout, name='checkout'),
    path('checkout/success/<int:order_id>/', views.checkout_success, name='checkout_success'),
    path('validate_discount/<str:discount_code>/', views.validate_discount, name='validate_discount'),
]

highlands/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('packages/', include('packages.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
     path('checkout/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from cart.models import Cart
from user.models import CustomUser
from packages.models import Package
from django_countries.fields import CountryField

class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    addressline_1 = models.CharField(max_length=50, blank=True)
    addressline_2 = models.CharField(max_length=50, blank=True)
    county = models.CharField(max_length=30, blank=True)
    country = CountryField(blank=True)
    phone_number = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return f'Order for {self.user.username}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    package = models.ForeignKey(Package, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.quantity} x {self.package.title}'


class Payment(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Payment for Order {self.order.id}'


class DiscountCode(models.Model):
    code = models.CharField(max_length=20, unique=True)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.code} - {self.discount_percentage}% Discount"

checkout/forms.py
from django import forms
from django_countries.fields import CountryField

class CheckoutForm(forms.Form):
    addressline_1 = forms.CharField()
    addressline_2 = forms.CharField(required=False)
    county = forms.CharField()
    country = CountryField().formfield()
    phone_number = forms.CharField()

    discount_code = forms.CharField(required=False)

checkout/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Order, OrderItem, Payment, DiscountCode
from .forms import CheckoutForm
from cart.models import Cart
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from decimal import Decimal
import stripe
from django.conf import settings


def create_order(request):
    cart = Cart.objects.filter(user=request.user)

    if not cart.exists():
        return redirect('cart:cart_view')

    total_price = sum(item.package.price * item.quantity for item in cart)
    
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            discount_code = form.cleaned_data.get('discount_code', '')
            discount_amount = calculate_discount(total_price, discount_code)

            order = Order.objects.create(
                user=request.user,
                total_price=total_price - discount_amount,
                discount_amount=discount_amount,
                addressline_1=form.cleaned_data['addressline_1'],
                addressline_2=form.cleaned_data['addressline_2'],
                county=form.cleaned_data['county'],
                country=form.cleaned_data['country'],
                phone_number=form.cleaned_data['phone_number'],
            )

            for cart_item in cart:
                OrderItem.objects.create(
                    order=order, package=cart_item.package, quantity=cart_item.quantity
                )

            Payment.objects.create(order=order, amount=total_price - discount_amount)

            cart.delete()

            return redirect('checkout:order_confirmation', order_id=order.id)
    else:
        form = CheckoutForm()

    return render(request, 'checkout/checkout.html', {'form': form, 'cart': cart, 'total_price': total_price})

def order_confirmation(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    return render(request, 'checkout/order_confirmation.html', {'order': order})

def checkout_success(request, order_id):
    
    order = Order.objects.get(pk=order_id)

    return render(request, 'checkout/checkout_success.html', {'order': order})

stripe.api_key = settings.STRIPE_SECRET_KEY

def process_checkout(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = sum(item.package.price * item.quantity for item in cart)

    stripe.api_key = settings.STRIPE_SECRET_KEY
    stripe_public_key = settings.STRIPE_PUBLIC_KEY

    stripe_public_key = settings.STRIPE_PUBLIC_KEY
    stripe_secret_key = settings.STRIPE_SECRET_KEY

    form = CheckoutForm()

    discount_amount = 0


    # Create a PaymentIntent
    intent = stripe.PaymentIntent.create(
        amount=int((total_price - discount_amount) * 100),
        currency='gbp',
        description='Order payment',
    )

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            

            discount_code = form.cleaned_data.get('discount_code', '')
            discount_amount = calculate_discount(total_price, discount_code)

            total_amount = total_price - discount_amount

            
            order = Order.objects.create(
                user=request.user,
                total_price=total_price - discount_amount,
                addressline_1=form.cleaned_data['addressline_1'],
                addressline_2=form.cleaned_data['addressline_2'],
                county=form.cleaned_data['county'],
                country=form.cleaned_data['country'],
                phone_number=form.cleaned_data['phone_number'],
            )

            for cart_item in cart:
                OrderItem.objects.create(
                    order=order, package=cart_item.package, quantity=cart_item.quantity
                )

            Payment.objects.create(order=order, amount=total_price - discount_amount)

            cart.delete()

            messages.success(request, 'Order placed successfully! Your Adventure Begins!')
            client_secret = intent.client_secret
            return render(request, 'checkout/checkout_success.html', {'order': order, 'client_secret': client_secret, 'public_key': stripe_public_key})
        else:
            messages.error(request, 'Error processing your order. Please try again.')
            return render(request, 'checkout/checkout.html', {'form': form, 'cart': cart, 'total_price': total_price, 'client_secret': client_secret, 'public_key': stripe_public_key})
            
            
    
    client_secret = intent.client_secret
    return render(request, 'checkout/checkout.html', {'form': form, 'cart': cart, 'total_price': total_price, 'client_secret': client_secret, 'public_key': stripe_public_key})





def calculate_discount(total_price, discount_code):
    if not discount_code:
        return 0  # No discount code provided

    try:
        code = DiscountCode.objects.get(code=discount_code)
        return total_price * (code.discount_percentage / 100)
    except DiscountCode.DoesNotExist:
        return 0  # Invalid discount code



def validate_discount(request, discount_code):
    try:
        code = DiscountCode.objects.get(code=discount_code)
        return JsonResponse({'valid': True, 'discount_percentage': float(code.discount_percentage)})
    except DiscountCode.DoesNotExist:
        return JsonResponse({'valid': False})

checkout/templates/checkout/checkout.html
{% extends "base.html" %}

{% block content %}
<div id="alert-container" class="container messages-container"></div>

<div class="container mt-5">
    <h1 class="mb-4">Checkout</h1>
    <form method="post" action="{% url 'checkout:checkout' %}" id="payment-form">
        {% csrf_token %}
        <!-- Shipping Information Section -->
        <h2>Shipping Information</h2>
        <div class="form-group">
            <label for="{{ form.addressline_1.id_for_label }}">Address Line 1:</label>
            {{ form.addressline_1 }}
        </div>

        <div class="form-group">
            <label for="{{ form.addressline_2.id_for_label }}">Address Line 2:</label>
            {{ form.addressline_2 }}
        </div>

        <div class="form-group">
            <label for="{{ form.county.id_for_label }}">County:</label>
            {{ form.county }}
        </div>

        <div class="form-group">
            <label for="{{ form.country.id_for_label }}">Country:</label>
            {{ form.country }}
        </div>

        <div class="form-group">
            <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
            {{ form.phone_number }}
        </div>

        <!-- Order Summary Section -->
        <h2>Order Summary</h2>
        <ul class="list-group mb-3">
            {% for cart_item in cart %}
                <li class="list-group-item">{{ cart_item.package.title }} - Quantity: {{ cart_item.quantity }}</li>
            {% endfor %}
        </ul>

        <!-- Discount Code Section -->
        <div class="form-group d-none">
            <label for="{{ form.discount_code.id_for_label }}">Discount Code:</label>
            <p>As a registered user, please use the discount code : <strong>HA10</strong> for a 10% discount!</p>
            {{ form.discount_code }}
            <button type="button" id="apply-discount" class="btn btn-primary mt-2">Apply Discount</button>
            <input type="hidden" id="discount-applied" value="false">
        </div>

        <!-- Updated Total Price Section -->
        <p class="mb-3">Total Price (without discount): £{{ total_price }}</p>
        <p class="mb-3">Total Price: £<span id="total-price">{{ total_price }}</span></p>
        <p><strong>We are experiencing technical difficulties with our discount code feature on the website. As a result, we regret to inform you that we are unable to process discount codes during the checkout process.
            However, we want to assure you that your loyalty is important to us, and to express our gratitude, we will credit a 10% discount to your bank account after the completion of your order. We understand the inconvenience this may cause and sincerely apologise for any frustration.
            Our team is actively working to resolve this issue, and we anticipate having the discount code functionality fully operational again in the near future. In the meantime, we appreciate your understanding and patience as we strive to enhance your shopping experience.</strong></p>

        <!-- Stripe Elements for Card Input Section -->
        <h4>Please enter your card details below</h4>
        <div id="card-element" class="form-group">
            <!-- A Stripe Element will be inserted here. -->
        </div>

        <!-- Used to display form errors. -->
        <div id="card-errors" class="alert alert-danger mt-3" role="alert"></div>

        <input type="hidden" id="client-secret" value="{{ client_secret }}">
        <input type="hidden" id="public-secret" value="{{ public_key }}">

        <!-- Submit Button -->
        <button type="submit" id="submit-button" class="btn btn-success">Submit</button>

    </form>
</div>
<script src="https://js.stripe.com/v3/"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const publicKey = document.getElementById('public-secret').value;
        var stripe = Stripe(publicKey); 
        var elements = stripe.elements();

        var card = elements.create('card');

        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission.
        var form = document.getElementById('payment-form');
        var submitButton = document.getElementById('submit-button');

        form.addEventListener('submit', function (event) {
            event.preventDefault();

            var clientSecret = document.getElementById('client-secret').value;

            stripe.confirmCardPayment(clientSecret, {
                payment_method: {
                    card: card,
                }
            }).then(function (result) {
                console.log('Stripe confirmCardPayment callback:', result);

                if (result.error) {
                    console.log('stripe error');
                    // Show error 
                    var errorElement = document.getElementById('card-errors');
                    errorElement.textContent = result.error.message;

                    // Re-enable the submit button on error
                    submitButton.disabled = false;
                } else {
                    console.log('stripe succeeded.')
                    // The payment succeeded!
                    form.submit();
                }
            });
        });
    });

    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('apply-discount').addEventListener('click', function () {
            applyDiscount();
        });
    });

    function applyDiscount() {
        var discountCode = document.getElementById('id_discount_code').value;

        // Check if discount has already been applied
        if (document.getElementById('discount-applied').value === 'true') {
            showAlert('Discount already applied.', 'warning');
            return;
        }

        fetch('/checkout/validate_discount/' + discountCode + '/')
            .then(response => response.json())
            .then(data => {
                // Check if the discount code is valid and fetch the discount percentage
                if (data.valid) {
                    var discountPercentage = data.discount_percentage;

                    // Calculate discounted total price
                    var totalPrice = parseFloat(document.getElementById('total-price').textContent);
                    var discountedPrice = totalPrice - (totalPrice * (discountPercentage / 100));

                    // Update the displayed total price
                    document.getElementById('total-price').textContent = discountedPrice.toFixed(2);

                    // Update the order summary for each item
                    var items = document.querySelectorAll('#order-summary li');
                    items.forEach(function (item) {
                        var originalPrice = parseFloat(item.textContent.match(/Price: \$([\d.]+)/)[1]);
                        var discountedItemPrice = originalPrice - (originalPrice * (discountPercentage / 100));
                        item.textContent = item.textContent.replace(/(Price: \$[\d.]+)/, 'Price: $' + discountedItemPrice.toFixed(2));
                    });

                    // Mark that the discount has been applied
                    document.getElementById('discount-applied').value = 'true';

                    // Display success message
                    showAlert('Discount applied successfully.', 'success');
                } else {
                    showAlert('Invalid discount code', 'danger');
                }
            })
            .catch(error => {
                console.error('Error:', error);
                showAlert('An error occurred while applying the discount.', 'danger');
            });
    }

    function showAlert(message, alertType) {
        var alertContainer = document.getElementById('alert-container');
        var alertDiv = document.createElement('div');
        alertDiv.classList.add('alert', 'alert-' + alertType, 'alert-dismissible', 'fade', 'show');
        alertDiv.role = 'alert';
        alertDiv.innerHTML = message +
            '<button type="button" class="close" data-dismiss="alert" aria-label="Close">' +
            '<span aria-hidden="true">&times;</span>' +
            '</button>';
        alertContainer.appendChild(alertDiv);
    }
</script>
{% endblock %}

checkout/templates/checkout/checkout_success.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1 class="mb-4">Order Confirmation</h1>
    <p class="lead">Thank you for your purchase. Your order has been confirmed.</p>

    <div class="row mt-5">
      <div class="col-md-6">
        <h2>Order Details</h2>
        <p><strong>User:</strong> {{ order.user.username }}</p>
        <p><strong>Total Price:</strong> £{{ order.total_price }}</p>

        <h3>Items Ordered</h3>
        <ul>
          {% for item in order.orderitem_set.all %}
            <li>{{ item.package.title }} - Quantity: {{ item.quantity }}</li>
          {% endfor %}
        </ul>
      </div>

      <div class="col-md-6">
        <h2>Shipping Information</h2>
        <p><strong>Address Line 1:</strong> {{ order.addressline_1 }}</p>
        <p><strong>Address Line 2:</strong> {{ order.addressline_2 }}</p>
        <p><strong>County:</strong> {{ order.county }}</p>
        <p><strong>Country:</strong> {{ order.country }}</p>
        <p><strong>Phone Number:</strong> {{ order.phone_number }}</p>
      </div>
    </div>
  </div>
{% endblock %}