cart/urls.py
from django.urls import path
from . import views
from .views import update_cart

app_name = 'cart'

urlpatterns = [
    path('add/<int:package_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('view/', views.view_cart, name='cart_view'),
    path('update/<int:item_id>/', update_cart, name='update_cart'),

]

highlands/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('packages/', include('packages.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
     path('checkout/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('reviews/', views.review_list, name='review_list'),
    path('add_review/<int:package_id>/', views.add_review, name='add_review'),
    path('reviews_list/', views.ReviewsListView.as_view(), name='reviews_list'),
    path('view_review/', views.view_review, name='view_review'),
    path('view_package_reviews/<int:package_id>/', views.view_package_reviews, name='view_package_reviews'),
    path('user-reviews/', views.UserReviewsView.as_view(), name='user_reviews'),
    path('review/<int:review_id>/update/', views.ReviewUpdateView.as_view(), name='review-update'),
    path('review/<int:review_id>/delete/', views.ReviewDeleteView.as_view(), name='review-delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta http-equiv="X-UA-Compatible" content="ie edge" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Explore outdoor adventures with Highland Adventures" />
    <meta name="keywords" content="outdoor, adventure, hiking, travel" />
    <meta name="author" content="Richard Burman" />
    {% endblock %}
    {% block extra_meta %}
    {% endblock %}
    {% block corecss %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    {% endblock %}
    {% block extra_css %}
    {% endblock %}
    {% block corejs %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/7ca4720f9a.js" crossorigin="anonymous"></script>
    {% endblock %}
    {% block extra_js %}
    {% endblock %}

    <title>Highland Adventures {% block extra_title %}{% endblock %}</title>
</head>

<body>
    <header class="container-fluid fixed-top"></header>
    <header class="container-fluid fixed-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand highland-adventures-brand" href="{% url 'home' %}">
                <i class="fas fa-hiking"></i> Highland Adventures
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'packages:package_list' %}">View Packages</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'about_us' %}">About Us</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'gallery' %}">Gallery</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'reviews:review_list' %}">Reviews</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'cart:cart_view' %}">Cart</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'reviews:user_reviews' %}">User Reviews</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">Logout</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            User Profile Details
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'user_profile' %}">User Profile</a>
                            <a class="dropdown-item" href="{% url 'user_profile_edit' %}">Edit User Profile</a>
                            <a class="dropdown-item" href="{% url 'custom_user_edit' %}">Edit Personal Details</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Register</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="nav-item {% if request.resolver_match.url_name == 'admin:index' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container messages-container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <main class="content-container">
        <div class="container table-responsive">
            {% block content %} {% endblock %}
        </div>
    </main>

    <footer>
        <div class="container">
            <h3>Connect with Us</h3>
        </div>
        <div class="container">
            <ul class="social-links">
                <li><a href="https://www.facebook.com" rel="noopener noreferrer" target="_blank">Facebook</a></li>
                <li><a href="https://www.twitter.com" rel="noopener noreferrer" target="_blank">Twitter</a></li>
                <li><a href="https://www.instagram.com" rel="noopener noreferrer" target="_blank">Instagram</a></li>
            </ul>
        </div>
        <div class="container">
            <p>&copy; 2023 Hiking Walks</p>
        </div>
    </footer>


    {% block page_header %} {% endblock %}
    {% block postloadjs %}
    <script>
        setTimeout(function () {
            let messages = document.querySelector(".messages-container");
            if (messages) {
                messages.innerHTML = '';
            }
        }, 2500);
    </script>
    {% endblock %}
</body>

</html>